### ISSUE TITLE
클라우드 서버 신청

### ISSUE THREAD

**Issue by jongfeel** [aralaa/ChocoChatbot#8]
![image](https://user-images.githubusercontent.com/17442457/58383978-59296900-8017-11e9-88b6-44c8c7bdebd6.png)

에뮬레이터와 다르게 클라우는 오늘까지네요

꼭 신청하세요!

**Comment by eun1234** [comment]
네네! 오늘 신청하려고 합니다!

**Comment by aralaa** [comment]
어제 신청 했습니다11
